name: Update API Data

on:
  push:
    branches:
    - master
    paths:
    - 'keyboards/**'
    - 'layouts/community/**'

jobs:
  api_data:
    runs-on: ubuntu-latest
    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Generate API Data
      run: qmk generate-api

    - name: Upload API Data
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'api_data'
        destination-github-username: 'qmk'
        destination-repository-name: 'keyboards'
        user-email: hello@qmk.fm
